### ISSUE TITLE
No files 

### ISSUE THREAD

**Issue by sharmilemurugaraj** [oferh/ng2-autocomplete#1]
Hi When I install this module I dont have any files except package and readme.txt.

Can you check?

**Comment by oferh** [comment]
Do you mean that `git clone https://github.com/oferh/ng2-autocomplete.git` doesn't clone the project or something else?

**Comment by sharmilemurugaraj** [comment]
I am getting only package.json and readme.txt when i clone the module

**Comment by oferh** [comment]
can you paste the exact command you are using? don't see any reason that you shouldn't get the files.
try to download the files from the [repo](https://github.com/oferh/ng2-autocomplete/archive/master.zip) and let me know if you get them all.

**Comment by oferh** [comment]
it looks like a git issue not related to this project
