### ISSUE TITLE
build error at ComponentRef

### ISSUE THREAD

**Issue by kpkantaw** [oferh/ng2-autocomplete#3]
build error at ComponentRef is not generic for autocomplete.ts where you do private listCmp: ComponentRef<AutocompleteList> = undefined;

VS 2015

**Comment by oferh** [comment]
@kpkantaw  can you provide some more details:
1. what version of typescript and node are used?
2. the build output
3. are you using `npm run build:dev` to run the project?

As a side note: the project is built and test only on linux & mac
